import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import { ThemeProvider } from '@/components/theme/theme-provider/theme-provider';
import Header from '@/components/layout/header/header';
import { ScrollArea } from '@/components/ui/scroll-area';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute={`class`}
          defaultTheme={`system`}
          enableSystem={true}
          disableTransitionOnChange={true}
        >
          <div className="flex min-h-screen flex-col">
            <Header />
            <div className="flex h-[calc(100dvh-4rem)] flex-col">
              <ScrollArea className="flex-1 px-4 pb-4">{children}</ScrollArea>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
